version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-python-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py
